name: centos-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/tubekit

jobs:

  build:

    runs-on: centos-latest

    steps:
    - name: setyum
      run: |
        cd /etc/yum.repos.d/
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        yum update -y
        yum install -y epel-release
        yum install cmake gcc gcc-c++ make git -y
        yum install openssl-devel -y
        mkdir protobuflib
        cd protobuflib
        git clone https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local -Dprotobuf_BUILD_TESTS=OFF ../ 
        make install
        git clone https://github.com/crust-hub/tubekit.git
        cd tubekit
        cd protocol
        make
        cd ..
        cmake .
        make
