name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/tubekit

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: create tag
      run: |
          SHA=${{ github.sha }}
          TAG=${IMAGE}:$(TZ=UTC-9 date '+%Y%m')-${SHA:0:7}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            TAG="${IMAGE}:latest"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo TAG $TAG 
      
    - name: login to dockerhub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: build docker image
      run: |
        docker build . -t ${{ env.TAG }}
        
    - name: push image
      run: |
        docker push ${{ env.TAG }}
  
  centos:

    runs-on: centos-latest

    steps:
    - name: setyum
      run: |
        cd /etc/yum.repos.d/
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        yum update -y
        yum install -y epel-release
        yum install cmake gcc gcc-c++ make git -y
        yum install openssl-devel -y
        mkdir protobuflib
        cd protobuflib
        git clone https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local -Dprotobuf_BUILD_TESTS=OFF ../ 
        make install
        git clone https://github.com/crust-hub/tubekit.git
        cd tubekit
        cd protocol
        make
        cd ..
        cmake .
        make


        
        
        
    
      
